### PR TITLE
Mostly adding a note about local versus global minima

### PR DESCRIPTION
**Pull request by jbpoline**

### CODE REVIEW

**Comment by matthew-brett** [comment]
Thanks for reading - that is kind of you.   I did think about putting the note about local minima in, but I found I really wanted to put an example into the notebook, to explain it properly, so in the end, I decided to try and explain that via the exercises - in fact - exactly as you suggested - by rotating the brain by 180 degrees and showing how it usually get's stuck in that minimum...

**Comment by jbpoline** [comment]
I guess I still think it is worth noting, even if you try to explain by
exercices - it is something that they should have constantly in mind when
hearing "optimization".
luv
JB

**Comment by matthew-brett** [comment]
Can you think of a way of generating the actual values for a cost function that does have a local minimum?

I had thought about the 180 degree rotation, the problem being that I would need to introduce rotation matrices and angles.  I can easily do that in the class itself, but the current doc is getting too long for a 30 minute homework.

**Comment by matthew-brett** [comment]
I added a section at the end - does that cover it?

**Pull request closed without merging**
